### PR TITLE
Fixed descendSearch: the package being searched should not be ignored wh...

### PR DESCRIPTION
**Pull request by jaccokrijnen**
...en looking at re-exported modules

This solves https://github.com/chrisdone/haskell-docs/issues/20 for me.

### CODE REVIEW

**Comment by chrisdone** [comment]
I suspect this may prevent cross-package re-exports.

**Comment by jaccokrijnen** [comment]
It seems to me that `descendSearch` excludes the package by giving `Just package` to `searchModuleIdent`, which in turn filters it from the packages to search (therefore failing when a different module of the same package has to be searched). I don't really see how that would influence cross-package re-exports?

**Comment by chrisdone** [comment]
If a re-export needs to descend into a different package but you've specified `(Just onlyLookInThisPackage)`?

**Comment by jaccokrijnen** [comment]
But `searchModuleIdent` looks at every package with the given module name (except for the one provided), right?

**Comment by chrisdone** [comment]
Ah, you're correct. `filterPrevious` is a misnomer (`filter` = "keep these", but `filterPrevious` = "exclude these"). I'll rename it.

**Comment by chrisdone** [comment]
Merged.

**Comment by chrisdone** [comment]
Bumped as 4.2.5. Thanks!

**Pull request closed without merging**
